/**
 * exportPdf.js — client-side PDF builder for the "Export" Settings items.
 *
 * Uses jsPDF + jspdf-autotable (already in package.json). Runs entirely in the
 * browser — no serverless function, consistent with the existing CSV approach
 * and fully usable in the PWA offline.
 *
 * Bundle-size note: jsPDF adds ~250 KB gzipped. It is already listed in
 * package.json so there is no new dependency; the chunk is lazy-imported here
 * so it is only loaded when the user actually taps "PDF summary".
 *
 * Layout (top → bottom):
 *   Branded header  — "JobProfit" wordmark left, businessName right
 *   Title + meta    — export title, generated date, derived date range
 *   Totals strip    — Invoiced £ · Costs £ · Profit £ (set totals)
 *   Jobs table      — 8 columns, zebra-striped, summary truncated to ~50 chars
 *   Footer          — page numbers + "Generated by JobProfit · jobprofit.app"
 *                     Non-Pro adds "Sent with JobProfit" to the footer.
 *
 * Out of scope v1:
 *   - Per-job pages, receipt thumbnails, charts
 *   - User date-range picker (range is always derived from data)
 *   - Logo image upload (businessName text is used instead)
 *
 * @param {object[]} rows      — output of deriveJobRows(jobs, receipts)
 * @param {object}   opts
 * @param {string}   opts.title        — "Records export" | "Everything export"
 * @param {string}   [opts.businessName] — shown in header right side
 * @param {boolean}  [opts.isPro]      — controls "Sent with JobProfit" footer line
 * @returns {Promise<Blob>}  — application/pdf Blob
 */

import { deriveJobRows, deriveAccountFields } from './exportCsv.js';

// Max chars for summary column before truncation
const SUMMARY_MAX = 50;

function truncate(str, max) {
  if (!str) return '';
  return str.length > max ? str.slice(0, max - 1) + '…' : str;
}

function fmtMoney(n) {
  return '£' + Number(n || 0).toFixed(2);
}

/**
 * Format a YYYY-MM-DD string as "13 Jun 2026". Returns '' on invalid input.
 */
function fmtDate(dateStr) {
  if (!dateStr) return '';
  const d = new Date(dateStr + 'T00:00:00');
  if (isNaN(d.getTime())) return dateStr;
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

/**
 * Derive the date range string from the rows: "1 Jan 2026 – 31 Dec 2026".
 * Uses job.date from each row. Falls back to "All jobs to date" if no dates present.
 */
function deriveDateRange(rows) {
  const dates = rows
    .map(r => r.date)
    .filter(Boolean)
    .sort();
  if (dates.length === 0) return 'All jobs to date';
  const first = fmtDate(dates[0]);
  const last = fmtDate(dates[dates.length - 1]);
  return first === last ? first : `${first} – ${last}`;
}

/**
 * Builds a PDF Blob from already-derived job rows.
 *
 * Separate from buildJobsPdf so the PDF builder can be tested without
 * re-running the aggregation logic (which is already tested in exportCsv tests).
 *
 * @param {object[]} rows          — output of deriveJobRows(jobs, receipts)
 * @param {object}   opts
 * @param {string}   opts.title        — "Records export" | "Everything export"
 * @param {string}   [opts.businessName] — shown in header right side
 * @param {boolean}  [opts.isPro]      — controls "Sent with JobProfit" footer line
 * @param {[string, string][]} [opts.accountFields] — when present, an Account section
 *                                        is rendered between the header and totals strip.
 *                                        Pass output of deriveAccountFields() for the
 *                                        "Export everything" PDF only.
 */
export async function buildPdfFromRows(rows, { title = 'Export', businessName = '', isPro = true, accountFields = null } = {}) {
  // Lazy-load jsPDF so the ~250 KB chunk is only fetched when needed
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();
  const MARGIN = 12;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  // ── Brand colours ──────────────────────────────────────────────────────────
  const GREEN = [37, 99, 235];   // #2563EB brand blue
  const BLACK = [11, 19, 32];    // #0B1320 Deep Navy
  const GREY  = [107, 114, 128]; // #6B7280
  const WHITE = [255, 255, 255];
  const STRIPE = [249, 250, 251]; // #F9FAFB — zebra even row

  // ── Header band ────────────────────────────────────────────────────────────
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, PAGE_W, 16, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...WHITE);
  doc.text('OHNAR', MARGIN, 11);

  if (businessName) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(businessName, PAGE_W - MARGIN, 11, { align: 'right' });
  }

  // ── Title + meta ───────────────────────────────────────────────────────────
  let y = 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...BLACK);
  doc.text(title, MARGIN, y);

  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...GREY);

  const generatedDate = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
  const dateRange = deriveDateRange(rows);

  doc.text(`Generated: ${generatedDate}`, MARGIN, y);
  doc.text(`Date range: ${dateRange}`, MARGIN + 60, y);

  // ── Account block (everything export only) ─────────────────────────────────
  // Rendered as a compact two-column grid (label | value) between the meta line
  // and the totals strip. Only included when accountFields is provided.
  if (Array.isArray(accountFields) && accountFields.length > 0) {
    y += 7;

    // Section heading
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BLACK);
    doc.text('Account details', MARGIN, y);

    y += 4;

    // Thin rule under heading
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, MARGIN + CONTENT_W, y);

    y += 4;

    // Two-column layout: label left, value right of label.
    // Non-empty fields only — skip blank values.
    const filledFields = accountFields.filter(([, v]) => v && v.trim() !== '');
    const COL_W = CONTENT_W / 2;
    const ROW_H = 4.5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);

    for (let i = 0; i < filledFields.length; i++) {
      const col = i % 2;
      const rowIdx = Math.floor(i / 2);
      const x = MARGIN + col * COL_W;
      const ry = y + rowIdx * ROW_H;

      doc.setTextColor(...GREY);
      doc.text(filledFields[i][0] + ':', x, ry);
      doc.setTextColor(...BLACK);
      doc.text(filledFields[i][1], x + 30, ry);
    }

    y += Math.ceil(filledFields.length / 2) * ROW_H + 3;
  }

  // ── Totals strip ───────────────────────────────────────────────────────────
  y += 8;

  const totalInvoiced = rows.reduce((s, r) => s + r.invoiced, 0);
  const totalCosts    = rows.reduce((s, r) => s + r.costs, 0);
  const totalProfit   = rows.reduce((s, r) => s + r.profit, 0);

  const stripH = 14;
  doc.setFillColor(243, 244, 246); // #F3F4F6
  doc.roundedRect(MARGIN, y, CONTENT_W, stripH, 2, 2, 'F');

  const colW = CONTENT_W / 3;
  const labels = ['Invoiced', 'Costs', 'Profit'];
  const values = [fmtMoney(totalInvoiced), fmtMoney(totalCosts), fmtMoney(totalProfit)];

  labels.forEach((label, i) => {
    const x = MARGIN + colW * i + colW / 2;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...GREY);
    doc.text(label, x, y + 4.5, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...BLACK);
    doc.text(values[i], x, y + 11, { align: 'center' });
  });

  y += stripH + 5;

  // ── Jobs table ─────────────────────────────────────────────────────────────
  const head = [['Date', 'Customer', 'Summary', 'Invoiced £', 'Costs £', 'Profit £', 'Status', 'Paid date']];

  const body = rows.map(r => [
    r.date,
    r.customer,
    truncate(r.summary, SUMMARY_MAX),
    r.invoiced.toFixed(2),
    r.costs.toFixed(2),
    r.profit.toFixed(2),
    r.status,
    r.paidDate,
  ]);

  autoTable(doc, {
    startY: y,
    head,
    body,
    margin: { left: MARGIN, right: MARGIN },
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: BLACK,
      lineColor: [229, 231, 235],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: GREEN,
      textColor: WHITE,
      fontStyle: 'bold',
      halign: 'left',
    },
    alternateRowStyles: {
      fillColor: STRIPE,
    },
    columnStyles: {
      0: { cellWidth: 22 },  // Date
      1: { cellWidth: 36 },  // Customer
      2: { cellWidth: 'auto' }, // Summary — takes remaining width
      3: { cellWidth: 22, halign: 'right' }, // Invoiced
      4: { cellWidth: 20, halign: 'right' }, // Costs
      5: { cellWidth: 20, halign: 'right' }, // Profit
      6: { cellWidth: 20 }, // Status
      7: { cellWidth: 22 }, // Paid date
    },
    didDrawPage: (data) => {
      // ── Footer on every page ──────────────────────────────────────────────
      const footerY = PAGE_H - 7;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...GREY);

      const footerLeft = isPro
        ? 'Generated by OHNAR · jobprofit.co.uk'
        : 'Generated by OHNAR · jobprofit.co.uk · Sent with OHNAR';

      doc.text(footerLeft, MARGIN, footerY);

      const pageCount = doc.internal.getNumberOfPages();
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}`,
        PAGE_W - MARGIN,
        footerY,
        { align: 'right' },
      );
    },
  });

  return doc.output('blob');
}

/**
 * Full entry point: aggregates jobs + receipts then builds the PDF.
 *
 * For "Export everything", pass opts.includeAccount = true together with
 * opts.profile and opts.session so the Account block is rendered above the
 * totals strip. "Export records" does not pass these — no Account block shown.
 *
 * @param {object[]} jobs
 * @param {object[]} receipts
 * @param {object}   opts
 * @param {string}   [opts.title]
 * @param {string}   [opts.businessName]
 * @param {boolean}  [opts.isPro]
 * @param {boolean}  [opts.includeAccount]  — when true, includes Account section
 * @param {object}   [opts.profile]         — profiles row (used with includeAccount)
 * @param {object}   [opts.session]         — Supabase session (used with includeAccount)
 * @returns {Promise<Blob>}
 */
export async function buildJobsPdf(jobs, receipts, opts = {}) {
  const rows = deriveJobRows(jobs, receipts);
  const { includeAccount, profile, session, ...pdfOpts } = opts;
  const accountFields = includeAccount ? deriveAccountFields(profile, session) : null;
  return buildPdfFromRows(rows, { ...pdfOpts, accountFields });
}
